[package]
name = "bridgec"
version = "0.1.0"
authors = ["yakirChen <iamyakirchen@outlook.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
cc = "1.0.48"

[[bin]]
name = "helloc_r"
path = "src/helloc_r.rs"
