[package]
name = "house"
version = "0.1.0"
authors = ["yakirChen <iamyakirchen@outlook.com>"]
edition = "2018"

[dependencies]
tarpc = { version = "0.20.0", features = ["full"] }
futures = "0.3.1"
tokio = { version = "0.2", features = ["full"] }
