####
# JVM mode
# mvn package
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/serverless-jvm .
# docker run -i --rm -p 8080:8080 quarkus/serverless-jvm
###
FROM fabric8/java-alpine-openjdk8-jre
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV AB_ENABLED=jmx_exporter
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
ENTRYPOINT [ "/deployments/run-java.sh" ]